config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from ninja import NinjaAPI

from paintings.routers import paints_router, users_router

api = NinjaAPI()
api.add_router("/users/", users_router)
api.add_router("/paints/", paints_router)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("paintings.urls", namespace="paintings")),
    path("api/", api.urls),
]


# settings를 사용하려면 이렇게 사용해야함. 장고가 그렇게 하라고 했기때문

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paintings/urls.py
from django.urls import path

from . import views as pt_views

app_name = "paintings"
urlpatterns = [
    path("", pt_views.sign_up_or_in, name="sign_up_or_in"),
    path("home/", pt_views.HomeView.as_view(), name="home"),
    path("create/", pt_views.create, name="create"),
    path("logout/", pt_views.log_out, name="logout"),
    path("avatar/", pt_views.avatar, name="avatar"),
    path("<str:username>/", pt_views.mypage, name="mypage"),
]

paintings/models.py
# from django.contrib.auth.models import User
from datetime import datetime, timedelta
from email.policy import default

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Create your models here.


class Painting(TimeStampedModel):
    class Meta:
        db_table = "painting"

    title = models.CharField(max_length=150)
    owner = models.ForeignKey("User", related_name="paintings", on_delete=models.CASCADE)
    upload_image = models.FileField(upload_to="upload_images", blank=True)
    image = models.ImageField(upload_to="paintings", blank=True)
    style = models.CharField(max_length=150, null=True)
    like_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def created_string(self):
        time = datetime.now() - self.created
        if time < timedelta(minutes=1):
            return "방금 전"
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + "분 전"
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + "시간 전"
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created.date()
            return str(time.days) + "일 전"
        else:
            return False


class Like(TimeStampedModel):
    paint = models.ForeignKey(Painting, related_name="likes", on_delete=models.CASCADE)
    owner = models.ForeignKey("User", related_name="likes", on_delete=models.CASCADE)

    class Meta:
        db_table = "like"
        constraints = [models.UniqueConstraint(fields=["paint", "owner"], name="unique_owner_paint")]

    def __str__(self):
        return f"paint : {self.paint} - owner : {self.owner}"


class User(AbstractUser):
    class Meta:
        db_table = 'user'
    avatar = models.ImageField(upload_to="avatars", default="avatars/sparta.png")

    class Meta:
        db_table = "user"

paintings/views.py
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth import logout
from django.views.generic import ListView

from .models import Painting, User


# Create your views here.


def sign_up_or_in(request):
    if request.user.is_authenticated:
        return redirect(reverse("paintings:home"))

    most_liked_paint = Painting.objects.all().order_by("-like_count")
    if most_liked_paint:
        return render(request, "sign_up_or_in.html", {"paint": most_liked_paint[0].image})

    return render(request, "sign_up_or_in.html")


@method_decorator(login_required, name="dispatch")
class HomeView(ListView):
    model = Painting
    template_name = "home.html"
    paginate_by = 2

    def get_ordering(self):
        ordering = self.request.GET.get("ordering", "-created")
        # validate ordering here
        return ordering

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ordering"] = self.request.GET.get("ordering", "-created")
        return context


# def home(request):
#     paintings = Painting.objects.all()
#     return render(request, "home.html", {"paintings": paintings})


@login_required(login_url="/")
def create(request):
    if request.method == "POST":
        user = request.user
        img_file = request.FILES["upload_img"]
        title = request.POST['title']
        style = request.POST['style']
        paint = request.POST['painting']
        Painting.objects.create(title=title, owner=user, upload_image=img_file, image=paint, style=style)
        return JsonResponse({"msg": "Post 작성"})
    return render(request, "create.html")


@login_required(login_url="/")
def mypage(request, username):
    try:
        user = User.objects.get(username=username)
        paintings = user.paintings.all().order_by("-created")
        return render(request, "mypage.html", {"paintings": paintings, "user": user})
    except User.DoesNotExist:
        return render(request, "404.html")


def log_out(request):
    print("hi")
    if request.user.is_authenticated:
        print("ho")
        logout(request)
    return redirect(reverse("paintings:sign_up_or_in"))



def avatar(request):

    image = request.FILES["img"]
    user = User.objects.get(pk=request.user.id)
    user.avatar = image
    user.save()

    return redirect(reverse("paintings:mypage", args=[user.username]))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Gothic+A1:wght@400;500;600;700&family=Nanum+Myeongjo:wght@400;700;800&family=Noto+Serif+KR:wght@300;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Gothic A1', sans-serif;
            font-family: 'Nanum Myeongjo', serif;
            font-family: 'Noto Serif KR', serif;
        }
    </style>
    {% block css %}
    {% endblock %}
</head>
<body>
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
    {% block script %}
    {% endblock %}
</body>
</html>

templates/create.html
{% extends 'base.html' %}
{% block title %} Seukka | Generate {% endblock %}
{% block css %}
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            width: 1200px;

        }


        .style-container {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .form-control {
            max-width: 300px;
        }

        h4 {
            background-color: #ffaf34;
            border-radius: 5px;
            padding: 0.3% 5%;
            margin: 15px 0;
        }
        {########## 파일 이미지 넣기 #############}
        canvas {
            width: 200px;
            height: 200px;
            border: 1px solid black;
            margin-bottom: 1%;
        }


        {# ######## 라디오 꾸미기#########}
        .radio-img {
            background-color: white;
            padding: 2% 2%;
            margin-bottom: 1%;
        }

        .radio-img input[type="radio"] {
            display: none;
        }

        .radio-img input[type="radio"]:checked + img {
            border: 4px solid #ffaf34;
        }

        .radio-img img {
            margin: 2% 2%;
            transition: .4s;
            cursor: pointer;
            border: 4px solid transparent;
            width: 200px;
            height: 160px;
        }

        {#################################}
        #preview {
            margin: 2% 0;
        }
        #create {
            margin-bottom: 10%;
        }


    </style>
{% endblock css %}
{% block content %}
    <div class="container">
        <h4>Title</h4>
        <input type="text" name="title" id="title">
        {#        <div class="filebox">#}
        {#            <label for="uplaod_img">Select base picture</label>#}
        {#            <input type="file" name="upload_img" id="uplaod_img" accept="image/*">#}
        {#        </div>#}
        {#        <input type="file" name="upload_img" id="upload_img" accept="image/*">#}

        <script src="http://www.dukelearntoprogram.com/course1/common/js/image/SimpleImage.js"></script>

        <h4>Select base picture</h4>

        <canvas id="can"></canvas>

        <input type="file" multiple="false" accept="image/*" id="upload_img" name="upload_img" onchange="upload()"/>

        <h4>Choose style options</h4>


        <div class="radio-img">
            <label>
                <input type="radio" name="radio" value="LSD">
                <img src="https://tekken.s3.ap-northeast-2.amazonaws.com/LSD.jpg">
            </label>
            <label>
                <input type="radio" name="radio" value="drug">
                <img src="https://tekken.s3.ap-northeast-2.amazonaws.com/drug.jpg" alt="drug">
            </label>
            <label>
                <input type="radio" name="radio" value="drug2">
                <img src="https://tekken.s3.ap-northeast-2.amazonaws.com/drug2.jpg" alt="drug2">
            </label>
            <label>
                <input type="radio" name="radio" value="drug3">
                <img src="https://tekken.s3.ap-northeast-2.amazonaws.com/drug3.jpg" alt="drug3">
            </label>
            <label>
                <input type="radio" name="radio" value="drug4">
                <img src="https://tekken.s3.ap-northeast-2.amazonaws.com/drug4.jpg" alt="drug4">
            </label>
            <label>
                <input type="radio" name="radio" value="hush">
                <img src="https://tekken.s3.ap-northeast-2.amazonaws.com/hush.jpg" alt="hush">
            </label>
            <label>
                <input type="radio" name="radio" value="kkm">
                <img src="https://tekken.s3.ap-northeast-2.amazonaws.com/kkm.jpg" alt="kkm">
            </label>

        </div>

        <button id="paint-submit" class="btn btn-warning">Start Convert</button>
        <img id="preview" src="">

        <button id="create" class="btn btn-warning">Create Post</button>
    </div>

{% endblock %}
{% block script %}

    <script>
        function upload() {
            let imgCanvas = document.getElementById("can");
            let fileInput = document.getElementById("upload_img");
            let image = new SimpleImage(fileInput);
            image.drawTo(imgCanvas);
        }

        const createBtn = document.getElementById('create')
        createBtn.addEventListener('click', (e) => {
            e.preventDefault()
            const title = document.getElementById('title').value
            const style = $("input[name=radio]:checked").val()
            const upload_img = $('#upload_img')[0].files[0]
            const painting = document.getElementById('preview').src
            const form_data = new FormData()
            form_data.append('title', title) //title
            form_data.append('style', style)//style
            form_data.append('painting', painting)//painting
            form_data.append('upload_img', upload_img) //img

            $.ajax({
                type: "POST",
                url: '/create/',
                contentType: false,
                processData: false,
                data: form_data,
                dataType: "JSON",
                success: function (json) {
                    alert(json['msg'])
                }
            });

        })
        const preview = document.getElementById('preview')
        const submitBtn = document.getElementById('paint-submit')
        submitBtn.addEventListener('click', (e) => {
            e.preventDefault()
            const title = document.getElementById('title').value
            const style = $("input[name=radio]:checked").val()
            const upload_img = $('#upload_img')[0].files[0]

            //인공지능 서버 스키마랑 같아야함. file, name, style
            const form_data = new FormData()
            form_data.append('file', upload_img)
            form_data.append('name', title)
            form_data.append('style', style)
            $.ajax({
                type: "POST",
                url: `http://183.97.229.232:5000/hello/${title}&${style}`,
                contentType: false,
                processData: false,
                data: form_data,
                dataType: "JSON",
                // 성공하면 preview의 src에 url넣어 출력
                success: function (json) {
                    console.log(json)
                    preview.src = json['hello']
                }
            });
        })
        // csrf token
        $.ajaxSetup({
            headers: {"X-CSRFToken": '{{csrf_token}}'}
        });


    </script>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
{% endblock %}
{% block content %}
    <div class="wrapper">
        <div class="ordering">
            <div>
                <a href="?ordering=-created">최신 순</a>
            </div>
            <div>
                <a href="?ordering=-like_count">좋아요 순</a>
            </div>

        </div>
        <div class="paintings infinite-container">

            {% for paint in object_list %}
                <div class="paint infinite-item">
                    <img class="imgs" src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{ paint.upload_image }}">
                    <img class="imgs" src="https://tekken.s3.ap-northeast-2.amazonaws.com/{{ paint.style }}.jpg">
                    <img class="imgs" src="{{ paint.image }}">
                    <div class="info-box">
                        <div class="first-box">
                            <img src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{ paint.owner.avatar }}" alt="">
                            <div class="title-box">
                                <h2>{{ paint.title }}</h2>
                                <p>{{ paint.created_string }}</p>
                            </div>
                        </div>
                        <div class="second-box">
                            <span>{{ paint.like_count }}</span>
                            <span class="like-btn">
                                <i class="fa-solid fa-heart fa-2x" data-id="{{ paint.id }}"></i>
                        </span>
                            {% if paint.owner == request.user %}
                                <span class="del-btn"><i class="fa-solid fa-trash-can fa-2x"
                                                         data-id="{{ paint.id }}"></i></span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}&ordering={{ ordering }}"></a>
            {% endif %}
        </div>
    </div>

{% endblock %}
{% block script %}
    <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
    <script src="{% static "js/infinite.min.js" %}"></script>
    <script>


        const likeAdd = (e) => {
            e.preventDefault()
            console.log(e)
            const paint_id = e.target.dataset.id
            const target = e.target.parentNode.parentNode.children[0].innerText
            $.ajax({
                type: "POST",
                url: `/api/paints/like/${paint_id}`,
                success: function (json) {
                    if (json.msg == 'delete') {
                        e.target.parentNode.parentNode.children[0].innerText = parseInt(target) - 1
                    } else if (json.msg == 'ok') {
                        e.target.parentNode.parentNode.children[0].innerText = parseInt(target) + 1
                    } else {
                        alert(json.msg)
                    }
                }
            });
        }
        const likeDel = (e) => {
            e.preventDefault()
            const paint_id = e.target.dataset.id
            $.ajax({
                type: "DELETE",
                url: `/api/paints/delete/${paint_id}`,
                success: function (json) {
                    if (json.msg == 'delete') {
                        alert('게시물이 삭제되었습니다.')
                        window.location.reload()
                    } else if (json.msg == 'err-user') {
                        alert('삭제 권한이 없습니다.')
                    } else if (json.msg == 'not founded') {
                        alert('게시물이 존재하지 않습니다.')
                    }
                }
            });
        }
        let likeBtns = document.querySelectorAll('.like-btn')
        for (i = 0; i < likeBtns.length; i++) {
            likeBtns[i].addEventListener('click', likeAdd)
        }

        let delBtns = document.querySelectorAll('.del-btn')
        for (i = 0; i < delBtns.length; i++) {
            delBtns[i].addEventListener('click', likeDel)
        }
        const infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            offset: 'bottom-in-view',
            onAfterPageLoad: function () {
                likeBtns = document.querySelectorAll('.like-btn')
                delBtns = document.querySelectorAll('.del-btn')
                for (i = 0; i < likeBtns.length; i++) likeBtns[i].removeEventListener('click', likeAdd)
                for (i = 0; i < delBtns.length; i++) delBtns[i].removeEventListener('click', likeDel)
                for (i = 0; i < likeBtns.length; i++) likeBtns[i].addEventListener('click', likeAdd)
                for (i = 0; i < delBtns.length; i++) delBtns[i].addEventListener('click', likeDel)


            }

        })

    </script>
{% endblock %}

templates/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/mypage.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
{% endblock %}
{% block content %}

<div class="header">
    <div class="header-info">
        <img src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{user.avatar}}" alt="">
        <div class="name-box">
            <h1>{{user.username}}</h1>
            {% if user.username == request.user.username%}
                <button type="button" class="btn btn-light" id="testBtn" data-toggle="modal" data-target="#exampleModal">
                    프로필 사진 변경
                </button>
            {%endif%}
              
        </div>
    </div>

</div>
<div class="bin">

</div>
{%if not paintings %}
<div class="empty-box">
    <h1>비어 있음</h1>
    <p>{{user.username}}의 <a href="/create">첫 번째</a> 그림을 만들어보세요 !</p>

</div>
{% endif %}
<div class="wrapper">

    <div class="paintings infinite-container">
        {%for paint in paintings %}
            <div class="paint infinite-item" >
                <img class="imgs" src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{paint.upload_image}}">
                <img class="imgs" src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{paint.upload_image}}">
                <img class="imgs" src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{paint.upload_image}}">
                <div class="info-box">
                    <div class="first-box">
                        <img src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{paint.owner.avatar}}" alt="">
                        <div class="title-box">
                            <h2>{{paint.title}}</h2>
                            <p>{{paint.created_string}}</p>
                        </div>
                    </div>
                    <div class="second-box">
                        <span>{{paint.like_count}}</span>
                        <span class="like-btn"  >
                                <i class="fa-solid fa-heart fa-2x" data-id="{{paint.id}}"></i>
                        </span>           
                        {% if paint.owner == request.user %}
                            <span class="del-btn" ><i class="fa-solid fa-trash-can fa-2x" data-id="{{paint.id}}"></i></span>
                        {% endif %}
                    </div>
                </div>  
            </div>
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="infinite-more-link" href ="?page={{ page_obj.next_page_number}}&ordering={{ordering}}"></a>
        {% endif %}
    </div>
</div>



<!-- Button trigger modal -->

  <!-- Modal -->
  <div class="modal fade" tabindex="-1" id="testModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">프로필 사진 변경</h5>
          </button>
        </div>
        <div class="modal-body">
            <form  method="POST" action="/avatar/" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="img"/>
                <button>전송</button>
            </form>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

{% endblock %}
{% block script %}
<script>
    $('#testBtn').click(function(e){
        e.preventDefault();
        $('#testModal').modal("show");
    });
    const likeAdd = (e) => {
        e.preventDefault()
        console.log(e)
        const paint_id = e.target.dataset.id
        const target = e.target.parentNode.parentNode.children[0].innerText
        $.ajax({
            type:"POST",
            url:`/api/paints/like/${paint_id}`,
            success : function(json) {
                if (json.msg == 'delete'){
                    e.target.parentNode.parentNode.children[0].innerText = parseInt(target) - 1
                } else if (json.msg == 'ok') {
                    e.target.parentNode.parentNode.children[0].innerText = parseInt(target) + 1
                } else {
                    alert(json.msg)
                }
            }
            });
    }
    const likeDel = (e) => {
        e.preventDefault()
        const paint_id = e.target.dataset.id
        $.ajax({
            type:"DELETE",
            url:`/api/paints/delete/${paint_id}`,
            success : function(json) {
                if (json.msg == 'delete') {
                    alert('게시물이 삭제되었습니다.')
                    window.location.reload()
                } else if (json.msg == 'err-user') {
                    alert('삭제 권한이 없습니다.')
                } else if (json.msg == 'not founded') {
                    alert('게시물이 존재하지 않습니다.')
                }
            }
            });
    }
    let likeBtns = document.querySelectorAll('.like-btn')
    for (i=0;i<likeBtns.length;i++){
        likeBtns[i].addEventListener('click',likeAdd)
    }
    
    let delBtns = document.querySelectorAll('.del-btn')
    for (i=0;i<delBtns.length;i++){
        delBtns[i].addEventListener('click',likeDel)
    }
</script>
{% endblock %}

templates/nav.html
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'paintings:home' %}">
            <img style="width: 100px;" src="https://sahayana-nts.s3.ap-northeast-2.amazonaws.com/SD_logo.png" alt=""/></a>
{#                <a class="navbar-brand" href="/home">Seukka Dream</a>#}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-1 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'paintings:home' %}">Home</a>
                    </li>
                    <li class="nav-item">                        
                        <a class="nav-link" href="#" >About</a>                       
                    </li>                    
                </ul>
                <div class="d-flex">
                    {% if user.is_authenticated %}
                        <button type="button" class="btn btn-warning" onclick="location.href='{% url 'paintings:create' %}'">Generate</button>
                        <a href="/{{ user.username }}" style="margin-left: 30px"><img src="https://sseoka.s3.ap-northeast-2.amazonaws.com/{{user.avatar}}" class="pic" style="border: 3px solid #dcdcdc; width:50px; height:50px; border-radius:50%;"/></a>
                    {% else %}
                        <a href="{% url 'paintings:sign_up_or_in' %}" style="margin-left: 1%">로그인</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </nav>
</header>

templates/sign_up_or_in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SeukkaDream | Sign</title>      
    <link rel="stylesheet" href="{% static 'css/sign.css' %}">

    <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

</head>
<body>
    <form class="sign">
        <div class="screen-1">
            <img class="logo" src="https://sahayana-nts.s3.ap-northeast-2.amazonaws.com/SD_logo.png" alt="logo.png" style="width: 300px; height: 300px;">
            <div class="id">
              <label for="id">Username</label>
              <div class="sec-2">
                <input type="text" id="username" name="username" placeholder="ID를 입력하세요.">
              </div>
            </div>
            <div class="password">
              <label for="password">Password</label>
              <div class="sec-2">          
                <input class="pas" id="current-password" type="password" name="password" placeholder="PW를 입력하세요."/>                
              </div>
            </div>
            <button class="login" id="signBtn" type="submit">Login or Register </button>
          </div>
    </form>


    <script>
        // 이 후에 css에서 처리
        document.body.style.backgroundImage= 'url(https://sseoka.s3.ap-northeast-2.amazonaws.com/{{paint}})'
        console.log('{{paint}}')
        const signBtn = document.querySelector('#signBtn')
        signBtn.addEventListener('click',(e)=>{
            e.preventDefault()
            const username =  document.querySelector('#username').value
            if (username == ''){
                return alert('아이디를 입력해주세요')
            }
            const password =  document.querySelector('#current-password').value
            $.ajax({
                type:"POST",
                data : {'username':username, 'password':password},
                url:'/api/users/sign',
                success : function(json) {
                    const msg = json.msg
                    if (msg == 'incorrect pw') alert('입력하신 정보가 일치하지 않습니다. ❗')
                    else if (msg == 'ok') window.location.href = '/home'
                    else alert(msg)
                }
                });
        })
        // csrf token
        $.ajaxSetup({
            headers: { "X-CSRFToken": '{{csrf_token}}' }
            });
    </script>

</body>
</html>